apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-app
  namespace: default
  labels:
    app: busybox-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
      - name: busybox
        image: invalid-image:nonexistent-tag
        command: ["sleep", "3600"]
        readinessProbe:
          exec:
            command: ["sh", "-c", "echo 'ready'"]
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command: ["sh", "-c", "echo 'alive'"]
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: busybox-2
        image: busybox:latest
        command: ["sleep", "3600"]
        readinessProbe:
          exec:
            command: ["sh", "-c", "echo 'ready'"]
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          exec:
            command: ["sh", "-c", "echo 'alive'"]
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"