apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-app
  namespace: default
  labels:
    app: busybox-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-app
  template:
    metadata:
      labels:
        app: busybox-app
    spec:
      containers:
      - name: busybox
        image: invalid-image:nonexistent-tag
        command: ["sleep", "3600"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: busybox-2
        image: busybox:latest
        command: ["sleep", "3600"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"